Repository openpmix/prrte, pull requests merged in 2018-12, with the labels that each got.

#145 Forward IO for indirect debugger case
  examples/debugger/indirect.c
Labels: Target: 3.0.x

#159 orte: plug misc memory leaks in orte_data_server()
  orte/runtime/orte_data_server.c
Labels: enhancement

#160 odls/base: plug a memory leak in orte_odls_base_default_construct_chi…
  orte/mca/odls/base/odls_base_default_fns.c
Labels: enhancement

#162 orted/pmix: correctly plug a memory leak
  orte/orted/pmix/pmix_server_dyn.c
Labels: bug

#161 iof/base: plug misc memory leaks
  orte/mca/iof/base/iof_base_frame.c
Labels: enhancement

#178 orted/pmix: plug a memory leak in _query()
  orte/orted/pmix/pmix_server_gen.c
Labels: enhancement

#180 state/base: fix a typo in _send_notification()
  orte/mca/state/base/state_base_fns.c
Labels: bug

#179 grpcomm/base: remove unused sig_table
  orte/mca/grpcomm/base/base.h
  orte/mca/grpcomm/base/grpcomm_base_frame.c
  orte/mca/grpcomm/base/grpcomm_base_stubs.c
Labels: code cleanup, enhancement
