Repository openpmix/prrte, pull requests merged in 2021-04, with the labels that each got.

#549 Proposal: remove pcc
  config/prte_config_files.m4
  src/tools/Makefile.am
  src/tools/pcc/Makefile.am
  src/tools/pcc/help-pcc.txt
  src/tools/pcc/pcc-wrapper-data.txt.in
  src/tools/pcc/pcc.1.md
  src/tools/pcc/pcc.c
Labels: CRITICAL, code cleanup

#924 Proposal: remove pcc
  config/prte_config_files.m4
  src/tools/Makefile.am
  src/tools/pcc/Makefile.am
  src/tools/pcc/help-pcc.txt
  src/tools/pcc/pcc-wrapper-data.txt.in
  src/tools/pcc/pcc.1.md
  src/tools/pcc/pcc.c
Labels: code cleanup

#889 Doc: Use 'qualifier' instead of 'modifier'
  src/tools/prte/prte-map.1.md
Labels: Documentation
